spring:
  config:
    import: optional:file:../.env[.properties],optional:file:.env[.properties]
  application:
    name: UserService
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:localhost:8848}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL:jdbc:mysql://localhost:3307/infinite_chat?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:}
  data:
    redis:
      database: ${REDIS_DATABASE:0}
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:59000}
      password: ${REDIS_PASSWORD:}
      timeout: ${REDIS_TIMEOUT:30s}
  mail:
    host: smtp.qq.com
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml

minio:
  url: ${MINIO_URL:http://localhost:9000}
  access-key: ${MINIO_ACCESS_KEY:}
  secret-key: ${MINIO_SECRET_KEY:}

server:
  port: 8104
